[["test.general.test_items.TestBase.test_item_name_group_conflict [Cat Food] (group_name='Cat Food', game_name='Manual_KotamaAcademyCitadel_bluepinkdragon')"]]
__expected__ = "fail"
__version__ = ">=0.0.1"

[["test.general.test_options.TestOptions.test_pickle_dumps_default (game='Manual_KotamaAcademyCitadel_bluepinkdragon', option='goal')"]]
__expected__ = "error"
__version__ = ">=0.0.1"
